### ISSUE TITLE
Ask for data

### ISSUE THREAD

**Issue by FrankenstainT** [carter-yagemann/MARSARA#1]
Hello, could you please share the data under the logs directory?
Thanks

Frank

**Comment by carter-yagemann** [comment]
Hi @FrankenstainT, I'm not sure if we have the logs from the original evaluation anymore. All the student authors graduated shortly after this work was published and the computer was reassigned to another student. Let me see what I can do.

**Comment by FrankenstainT** [comment]
Well, could you please tell me the detailed method of regenerating these data? It would be nice to open source the code for the Offline Profiling and Online Auditing stages so that I can get this project running.
